/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */
plugins {
    `java-library` // Wir bauen eine Library (Mod)
}

repositories {
    mavenCentral()
}

// Der Pfad zu deiner Hytale-Installation
val hytaleJarPath = "/home/vasilis/.var/app/com.hypixel.HytaleLauncher/data/Hytale/install/release/package/game/latest/Server/HytaleServer.jar"
val hytaleModsDir = "/home/vasilis/.var/app/com.hypixel.HytaleLauncher/data/Hytale/UserData/Mods"
val deploy = tasks.register<Copy>("deploy") {
    group = "deployment"
    description = "Kopiert die Mod in den Hytale-Ordner."

    // Warte, bis die JAR-Datei gebaut wurde
    dependsOn(tasks.jar)

    // Quelle: Die JAR-Datei, die Gradle gerade erzeugt hat
    from(tasks.jar.get().archiveFile)

    // Ziel: Dein Hytale Mods-Ordner
    into(hytaleModsDir)
}

dependencies {
    // Nutze compileOnly, da die JAR beim Starten von Hytale schon da ist
    compileOnly(files(hytaleJarPath))

    // Test-Framework (optional)
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

tasks.test {
    useJUnitPlatform()
}
tasks.build {
    finalizedBy(deploy)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21)) // Hytale nutzt wahrscheinlich Java 17
    }
}
